name: flutter_abc_jsc_components
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  figma_squircle: ^0.5.3
  cached_network_image: any
  extended_text: any
  flutter_html: ^3.0.0-alpha.6
#  flutter_html_math: ^3.0.0-alpha.3
  flutter_svg: ^2.0.7
  oktoast: ^3.3.1
  awesome_dialog: ^3.1.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  video_player: ^2.7.0
  realm: ^1.3.0
  json_annotation: ^4.8.1
  encrypt: ^5.0.1
  path_drawing: ^1.0.1


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
