name: flutter_abc_jsc_components
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.2
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.5
  pinput: ^4.0.0
  provider: ^6.1.2
  syncfusion_flutter_charts: ^25.2.4
  gif: ^2.3.0
  stroke_text: ^0.0.3
  carousel_slider: ^4.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 400
          style: italic